const canvas=document.querySelector('#assembly-canvas');
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const scenarios={peak:{values:{throughput:5,variability:3,operator:2,service:2},state:'Integrated pilot — ready to validate',headline:'Protect flow without losing bowl-level truth.',summary:'The release should preserve throughput while keeping portion evidence, operator recovery, and service signals visible enough to learn from the rush rather than merely survive it.',evidence:['Throughput','Order latency','Dispense accuracy','Interventions','Recovery time']},menu:{values:{throughput:3,variability:5,operator:3,service:2},state:'Recipe contract — validate the range',headline:'Scale variety through bounded recipe behavior.',summary:'A new menu is product work across food behavior, dispenser parameters, software configuration, loading, quality checks, and economics. The contract makes the acceptable range explicit before rollout.',evidence:['Recipe yield','Weight variance','Ingredient behavior','Changeover time','Waste']},pilot:{values:{throughput:4,variability:3,operator:4,service:3},state:'Pilot evidence — build the repeatable launch',headline:'Make the next installation easier than the last.',summary:'The pilot should test more than machine output. It should prove onboarding, order integration, operator routines, support ownership, site economics, and a clean path from field signal to product decision.',evidence:['Install readiness','Time to first bowl','Training load','Support demand','Unit economics']},service:{values:{throughput:2,variability:2,operator:4,service:5},state:'Service learning — restore and retain',headline:'Turn every recovery into product memory.',summary:'A maintenance event is a product-learning moment. Good instrumentation connects fault context, operator action, component access, time to recover, and the requirement or design decision that prevents recurrence.',evidence:['Fault context','Diagnosis time','Access steps','Time to restore','Repeat incidence']}};
const ranges={throughput:document.querySelector('#throughput'),variability:document.querySelector('#variability'),operator:document.querySelector('#operator'),service:document.querySelector('#service')};
const readout={state:document.querySelector('#readout-state'),headline:document.querySelector('#readout-headline'),summary:document.querySelector('#readout-summary'),cells:[...document.querySelectorAll('.evidence-cell strong')]};
let activeScenario='peak';let customAdjusted=false;
function valuesFromRanges(){return Object.fromEntries(Object.entries(ranges).map(([key,input])=>[key,input?Number(input.value):3]))}
function emitContractChange(values){window.dispatchEvent(new CustomEvent('lab37:contractchange',{detail:{values,scenario:activeScenario}}))}
function updateReadout(){const values=valuesFromRanges();const base=scenarios[activeScenario];const spread=Math.max(...Object.values(values))-Math.min(...Object.values(values));const pressure=values.throughput+values.variability;const resilience=values.operator+values.service;let{state,headline,summary}=base;if(customAdjusted&&spread>=4){state='Refine the product contract';headline='One constraint is outrunning the system.';summary=`This illustrative state makes the trade-off visible: ${values.throughput>=5?'throughput pressure':values.variability>=5?'recipe variability':values.operator>=5?'operator demand':'service access'} needs an explicit acceptance test and owner before the release can remain coherent.`}else if(customAdjusted&&pressure>=8&&resilience<=5){state='Validate recovery under load';headline='Speed needs an equally clear recovery path.';summary='Validate intervention frequency, fault context, and time to restore alongside throughput so fast operation also produces fast learning.'}else if(customAdjusted&&resilience>=8&&pressure<=5){state='Ready to simplify the operating burden';headline='Serviceability can become a scaling advantage.';summary='Strong operator and service conditions create room to standardize training, maintenance, support ownership, and launch readiness while the product continues to expand.'}if(readout.state)readout.state.textContent=state;if(readout.headline)readout.headline.textContent=headline;if(readout.summary)readout.summary.textContent=summary;readout.cells.forEach((cell,index)=>{cell.textContent=base.evidence[index]||''});Object.entries(ranges).forEach(([key,input])=>{const output=document.querySelector(`[data-output="${key}"]`);if(output&&input)output.textContent=input.value});emitContractChange(values)}
function setScenario(key){if(!scenarios[key])return;activeScenario=key;customAdjusted=false;document.querySelectorAll('.scenario-button').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.scenario===key)));Object.entries(scenarios[key].values).forEach(([name,value])=>{if(ranges[name])ranges[name].value=value});updateReadout()}
function bindControls(){const list=document.querySelector('.scenario-list');list?.addEventListener('click',event=>{const button=event.target.closest('.scenario-button');if(button)setScenario(button.dataset.scenario)});list?.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','ArrowRight','ArrowLeft'].includes(event.key))return;const buttons=[...list.querySelectorAll('.scenario-button')];const index=buttons.indexOf(document.activeElement);if(index<0)return;event.preventDefault();const direction=['ArrowDown','ArrowRight'].includes(event.key)?1:-1;const next=buttons[(index+direction+buttons.length)%buttons.length];next.focus();next.click()});Object.values(ranges).forEach(input=>input?.addEventListener('input',()=>{customAdjusted=true;updateReadout()}));document.querySelector('#reset-simulator')?.addEventListener('click',()=>setScenario('peak'))}
function installCyclePanel(){const stage=document.querySelector('.hero-stage');if(!stage||stage.querySelector('.stage-cycle'))return;const panel=document.createElement('div');panel.className='stage-cycle';panel.setAttribute('aria-live','polite');panel.innerHTML='<span id="cycle-bowl">Bowl 01</span><strong id="cycle-phase">Ingredients in flight</strong><button id="replay-assembly" type="button">Replay cycle</button><i class="cycle-track" aria-hidden="true"><b id="cycle-progress"></b></i>';stage.appendChild(panel)}
installCyclePanel();bindControls();setScenario('peak');
if(canvas){import('./animation-v4.js').then(({initBowlAssembly})=>initBowlAssembly({canvas,reduceMotion})).catch(error=>{console.warn('Bowl assembly enhancement unavailable:',error);document.querySelector('.hero-stage')?.classList.add('is-fallback')})}
